## Deliverable 2. Create a Customer Travel Destinations Map.

In [25]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [26]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()
print(os.getcwd())

/Users/snehalborhade/Desktop/UT_Austin_BootCamp/Challenges/Challenge_6/WeatherPy/Vacation_Search

In [38]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [39]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Current Description
1,1,Rikitea,PF,-23.1203,-134.9692,72.86,77,4,3.00,2022-07-20 15:21:18,light rain
2,2,Hermanus,ZA,-34.4187,19.2345,56.80,65,3,6.11,2022-07-20 15:21:16,clear sky
3,3,Kedrovyy,RU,56.1667,91.8167,59.41,95,96,4.90,2022-07-20 15:25:12,overcast clouds
4,4,Torbay,CA,47.6666,-52.7314,72.37,74,75,23.02,2022-07-20 15:25:12,broken clouds
5,5,Kodiak,US,57.7900,-152.4072,51.31,82,20,4.61,2022-07-20 15:21:23,few clouds
6,6,Tuktoyaktuk,CA,69.4541,-133.0374,57.20,77,75,11.50,2022-07-20 15:25:13,broken clouds
7,7,Avarua,CK,-21.2078,-159.7750,73.45,68,75,13.80,2022-07-20 15:25:13,broken clouds
8,8,Linxia,CN,35.6003,103.2064,64.18,68,64,2.66,2022-07-20 15:25:14,broken clouds
9,9,Nikolskoye,RU,59.7035,30.7861,73.29,50,97,12.55,2022-07-20 15:25:14,overcast clouds
10,10,Puerto Escondido,MX,15.8500,-97.0667,85.03,74,40,5.75,2022-07-20 15:25:12,scattered clouds

In [40]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                43
City                   43
Country                43
Lat                    43
Lng                    43
Max Temp               43
Humidity               43
Cloudiness             43
Wind Speed             43
Date                   43
Current Description    43
dtype: int64

In [41]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date,Current Description
1,1,Rikitea,PF,-23.1203,-134.9692,72.86,77,4,3.00,2022-07-20 15:21:18,light rain
2,2,Hermanus,ZA,-34.4187,19.2345,56.80,65,3,6.11,2022-07-20 15:21:16,clear sky
3,3,Kedrovyy,RU,56.1667,91.8167,59.41,95,96,4.90,2022-07-20 15:25:12,overcast clouds
4,4,Torbay,CA,47.6666,-52.7314,72.37,74,75,23.02,2022-07-20 15:25:12,broken clouds
5,5,Kodiak,US,57.7900,-152.4072,51.31,82,20,4.61,2022-07-20 15:21:23,few clouds
6,6,Tuktoyaktuk,CA,69.4541,-133.0374,57.20,77,75,11.50,2022-07-20 15:25:13,broken clouds
7,7,Avarua,CK,-21.2078,-159.7750,73.45,68,75,13.80,2022-07-20 15:25:13,broken clouds
8,8,Linxia,CN,35.6003,103.2064,64.18,68,64,2.66,2022-07-20 15:25:14,broken clouds
9,9,Nikolskoye,RU,59.7035,30.7861,73.29,50,97,12.55,2022-07-20 15:25:14,overcast clouds
10,10,Puerto Escondido,MX,15.8500,-97.0667,85.03,74,40,5.75,2022-07-20 15:25:12,scattered clouds

In [42]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,72.86,light rain,-23.1203,-134.9692,
2,Hermanus,ZA,56.80,clear sky,-34.4187,19.2345,
3,Kedrovyy,RU,59.41,overcast clouds,56.1667,91.8167,
4,Torbay,CA,72.37,broken clouds,47.6666,-52.7314,
5,Kodiak,US,51.31,few clouds,57.7900,-152.4072,
6,Tuktoyaktuk,CA,57.20,broken clouds,69.4541,-133.0374,
7,Avarua,CK,73.45,broken clouds,-21.2078,-159.7750,
8,Linxia,CN,64.18,broken clouds,35.6003,103.2064,
9,Nikolskoye,RU,73.29,overcast clouds,59.7035,30.7861,
10,Puerto Escondido,MX,85.03,scattered clouds,15.8500,-97.0667,

In [43]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()

    # 6f. Grab the first hotel from the results and store the name.if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
        continue
    
hotel_df.head(10)

Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,72.86,light rain,-23.1203,-134.9692,People ThankYou
2,Hermanus,ZA,56.80,clear sky,-34.4187,19.2345,Misty Waves Boutique Hotel
3,Kedrovyy,RU,59.41,overcast clouds,56.1667,91.8167,
4,Torbay,CA,72.37,broken clouds,47.6666,-52.7314,Gallows Cove
5,Kodiak,US,51.31,few clouds,57.7900,-152.4072,Best Western Kodiak Inn And Convention Center
6,Tuktoyaktuk,CA,57.20,broken clouds,69.4541,-133.0374,End of The Road Ltd.
7,Avarua,CK,73.45,broken clouds,-21.2078,-159.7750,Paradise Inn
8,Linxia,CN,64.18,broken clouds,35.6003,103.2064,GreenTree Inn Linxia Autonomous Prefecture Lin...
9,Nikolskoye,RU,73.29,overcast clouds,59.7035,30.7861,Tourist House - Sablino
10,Puerto Escondido,MX,85.03,scattered clouds,15.8500,-97.0667,Aldea del Bazar Hotel and Spa

In [44]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,72.86,light rain,-23.1203,-134.9692,People ThankYou
2,Hermanus,ZA,56.80,clear sky,-34.4187,19.2345,Misty Waves Boutique Hotel
3,Kedrovyy,RU,59.41,overcast clouds,56.1667,91.8167,
4,Torbay,CA,72.37,broken clouds,47.6666,-52.7314,Gallows Cove
5,Kodiak,US,51.31,few clouds,57.7900,-152.4072,Best Western Kodiak Inn And Convention Center
6,Tuktoyaktuk,CA,57.20,broken clouds,69.4541,-133.0374,End of The Road Ltd.
7,Avarua,CK,73.45,broken clouds,-21.2078,-159.7750,Paradise Inn
8,Linxia,CN,64.18,broken clouds,35.6003,103.2064,GreenTree Inn Linxia Autonomous Prefecture Lin...
9,Nikolskoye,RU,73.29,overcast clouds,59.7035,30.7861,Tourist House - Sablino
10,Puerto Escondido,MX,85.03,scattered clouds,15.8500,-97.0667,Aldea del Bazar Hotel and Spa

In [45]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [46]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [47]:
# 11a. Add a marker layer for each city to the map. 

# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11 b. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))